name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          
      - name: Install dependencies
        run: pdm install
        
      - name: Build package and Publish to PyPI
        run: pdm publish
        env:
          PDM_REQUEST_TIMEOUT: 300

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          build-args: |
            VERSION=${{ steps.version.outputs.VERSION }}
          tags: |
            thegeektechworkshop/bambu-cli:latest
            thegeektechworkshop/bambu-cli:${{ steps.version.outputs.VERSION }}